### PR TITLE
Feature/user interfaces

### PR DESCRIPTION
**Pull request by hariclerry**
i added user interfaces and UML diagram for the application as part of challenge one, please review and let me know what you think.

### CODE REVIEW

**Comment by peterwade153** [comment]
Nice work, maybe some those empty lines. but everything looks okay to me

**Comment by hariclerry** [comment]
i added user interfaces and UML diagram for the application as part of challenge one, please review and let me know what you think.

**Comment by hariclerry** [comment]
Thanks peter

**Comment by collin5** [comment]
Nice work!, Though your UML class diagrams are not well detailed enough. Checkout https://www.youtube.com/watch?v=3cmzqZzwNDM&t=7s for guidance.

**Comment by hariclerry** [comment]
@collin5, thanks. I will check out the youtube link and work on the UML diagrams

**Pull request merged**
